# Generated by Django 6.0.1 on 2026-02-24 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DOTACION', 'Archivo de Fichas (Dotación)'), ('ASISTENCIA', 'Archivo de Asistencia (Estadía)')], max_length=20)),
                ('archivo', models.FileField(upload_to='cargas/%Y/%m/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('log_errores', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga de Información',
                'verbose_name_plural': 'Cargas de Información',
            },
        ),
    ]
