# Generated by Django 6.0.1 on 2026-02-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='RUT')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('centro_costo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Dotación (Colaboradores)',
            },
        ),
    ]
