# Generated by Django 6.0.1 on 2026-02-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='RUT')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('centro_costo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, help_text='Para cálculo de antigüedad y contrataciones', null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('escolaridad', models.CharField(blank=True, max_length=100, null=True)),
                ('es_recomendable', models.BooleanField(default=True, help_text='Basado en campo Recomendable del Excel')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Dotación Completa',
            },
        ),
    ]
