# Generated by Django 6.0.1 on 2026-02-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='codigo_ficha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado_ficha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='fecha_termino_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='seccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='turno',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='es_recomendable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
