# Generated by Django 6.0.1 on 2026-02-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Dotación Completa'},
        ),
        migrations.AddField(
            model_name='colaborador',
            name='comuna',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='es_recomendable',
            field=models.BooleanField(default=True, help_text='Basado en campo Recomendable del Excel'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='escolaridad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Para cálculo de antigüedad y contrataciones', null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
