# Generated by Django 6.0.1 on 2026-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0002_colaborador_area_colaborador_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='activo',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('FINIQUITADO', 'Finiquitado'), ('BLOQUEADO', 'Bloqueado')], db_index=True, default='VIGENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='motivo_bloqueo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
