# Generated by Django 6.0.1 on 2026-02-25 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0003_remove_colaborador_activo_colaborador_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('VIGENTE', 'Vigente'), ('FINIQUITADO', 'Finiquitado'), ('BLOQUEADO', 'Bloqueado')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('VIGENTE', 'Vigente'), ('FINIQUITADO', 'Finiquitado'), ('BLOQUEADO', 'Bloqueado')], max_length=20)),
                ('motivo', models.TextField(help_text='Obligatorio al bloquear')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_realizados', to=settings.AUTH_USER_MODEL)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='dotacion.colaborador')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-fecha'],
            },
        ),
    ]
