# Generated by Django 6.0.1 on 2026-02-25 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0004_historialestado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaBloqueada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('motivo', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='bloqueados/')),
                ('fecha_bloqueo', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('bloqueado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_bloqueadas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona Bloqueada',
                'verbose_name_plural': 'Lista de Bloqueados',
                'ordering': ['-fecha_bloqueo'],
            },
        ),
    ]
