# Generated by Django 6.0.1 on 2026-02-10 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('dotacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('archivo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cargainformacion')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='dotacion.colaborador')),
            ],
            options={
                'verbose_name': 'Registro Diario',
                'verbose_name_plural': 'Registros de Asistencia',
                'unique_together': {('colaborador', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUSENCIA', 'Ausencia Injustificada'), ('ATRASO', 'Atraso en Entrada'), ('SIN_MARCA', 'Falta Marca Salida'), ('TURNO_EXTRA', 'Asistencia fuera de turno')], max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='asistencia.registroasistencia')),
            ],
        ),
    ]
