# Generated by Django 6.0.1 on 2026-02-04 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('codigo_ficha', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('seccion', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_ficha', models.CharField(default='Vigente', max_length=20)),
                ('turno', models.CharField(blank=True, help_text='Turno asignado en Grex', max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('escolaridad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='ReglaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Turno Día Packing', max_length=50)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('seccion', models.CharField(blank=True, max_length=100, null=True)),
                ('palabra_clave_turno', models.CharField(blank=True, help_text="Texto que debe contener el turno del colaborador para aplicar esta regla. Ej: '08:00' o 'NOCHE'", max_length=50, null=True)),
                ('entrada_teorica', models.TimeField()),
                ('salida_teorica', models.TimeField()),
                ('es_turno_noche', models.BooleanField(default=False, help_text='Marcar si la jornada termina al día siguiente.')),
                ('inicio_colacion', models.TimeField()),
                ('fin_colacion', models.TimeField()),
                ('tiempo_maximo_colacion', models.IntegerField(default=60)),
                ('holgura_minutos', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('FALTA', 'Ausencia injustificada'), ('ATRASO', 'Atraso en entrada'), ('SALIDA_ANTICIPADA', 'Salida antes de hora'), ('EXCESO_COLACION', 'Exceso tiempo colación'), ('IMPAR', 'Marcaje impar (falta entrada o salida)')], max_length=50)),
                ('detalle', models.TextField(blank=True)),
                ('minutos_perdidos', models.IntegerField(default=0)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.colaborador')),
            ],
            options={
                'verbose_name': 'Anomalía Detectada',
                'unique_together': {('colaborador', 'fecha', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Marcaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcajes', to='asistencia.colaborador')),
            ],
            options={
                'verbose_name': 'Marcaje',
                'unique_together': {('colaborador', 'fecha', 'hora')},
            },
        ),
    ]
