# Generated by Django 6.0.1 on 2026-02-25 14:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('estado_dotacion', models.CharField(choices=[('VIGENTE', 'Vigente'), ('FINIQUITADO', 'Finiquitado'), ('BLOQUEADO', 'Bloqueado'), ('EXTERNO', 'Externo / No encontrado')], default='EXTERNO', max_length=20)),
                ('quien_autoriza', models.CharField(max_length=100)),
                ('a_quien_visita', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=20)),
                ('patente', models.CharField(blank=True, max_length=15)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Visita',
                'verbose_name_plural': 'Registro de Visitas',
                'ordering': ['-hora_entrada'],
            },
        ),
    ]
