# Generated by Django 6.0.1 on 2026-02-24 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(help_text='Nombre del Jefe/Gerente', max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha_necesidad', models.DateField(help_text='¿Para cuándo se necesita?')),
                ('motivo', models.TextField(blank=True, help_text='Ej: Reemplazo, Aumento de temporada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('ABIERTA', 'Buscando Candidatos'), ('CERRADA', 'Completada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(help_text='Número de WhatsApp', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto_cedula_frente', models.ImageField(blank=True, null=True, upload_to='candidatos/cedulas/')),
                ('foto_cedula_dorso', models.ImageField(blank=True, null=True, upload_to='candidatos/cedulas/')),
                ('foto_selfie', models.ImageField(blank=True, null=True, upload_to='candidatos/selfies/')),
                ('estado', models.CharField(choices=[('NUEVO', 'Recién llegado (Bot)'), ('REVISION', 'En revisión de documentos'), ('APTO', 'Aprobado para entrevista'), ('CONTRATADO', 'Contratado (Enviar a Grex)'), ('DESCARTADO', 'Descartado')], default='NUEVO', max_length=20)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('observacion_ia', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(default='INICIO', max_length=50)),
                ('solicitud_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclutamiento.solicituddotacion')),
            ],
        ),
    ]
