# Generated by Django 6.0.1 on 2026-02-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='stage',
            field=models.CharField(default='INICIO', max_length=50),
        ),
    ]
