# Generated by Django 6.0.1 on 2026-02-24 20:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('empresa_externa', models.BooleanField(default=False, help_text='¿Es externo?')),
                ('nombre_empresa_externa', models.CharField(blank=True, help_text='Completar solo si es externo', max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Planta - Centro', max_length=100)),
                ('origen', models.CharField(default='Planta Aurora', max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('BUS', 'Bus'), ('MINIBUS', 'Minibús'), ('VAN', 'Van'), ('VAN_EMPRESA', 'Van-Empresa'), ('AUTO', 'Automóvil'), ('CAMIONETA', 'Camioneta')], max_length=20)),
                ('capacidad', models.IntegerField(help_text='Número de pasajeros')),
                ('tarifa_base', models.IntegerField(default=0, help_text='Costo estándar por servicio de este vehículo')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTransporteExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.CharField(blank=True, max_length=50, null=True)),
                ('turno', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(max_length=100)),
                ('tipo_maquina', models.CharField(max_length=20)),
                ('tarifa', models.IntegerField(default=0)),
                ('n_pasajeros', models.IntegerField(default=0)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro Transporte Excel',
                'verbose_name_plural': 'Registros Transporte Excel',
                'ordering': ['-fecha', 'turno', 'sector'],
                'unique_together': {('fecha', 'turno', 'sector', 'tipo_maquina')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_viaje', models.DateTimeField()),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('cantidad_pasajeros', models.IntegerField()),
                ('motivo', models.TextField(blank=True)),
                ('km_recorridos', models.IntegerField(default=0)),
                ('costo_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_RUTA', 'En Ruta'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.conductor')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_transporte', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paradas_intermedias', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_pasajeros', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo_movimiento', models.CharField(choices=[('SALIDA', 'Salida (Desde Planta)'), ('ENTRADA', 'Entrada (Hacia Planta)')], default='SALIDA', max_length=10)),
                ('ocupacion_porcentaje', models.FloatField(default=0, editable=False)),
                ('valor_viaje', models.IntegerField(default=0, help_text='Costo final del servicio (Editable por Admin)')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.conductor')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.ruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.vehiculo')),
            ],
            options={
                'ordering': ['-fecha_registro', '-id'],
            },
        ),
    ]
