# Generated by Django 6.0.1 on 2026-02-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='nombre_empresa_externa',
            field=models.CharField(blank=True, help_text='Completar solo si es externo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrosalida',
            name='tipo_movimiento',
            field=models.CharField(choices=[('SALIDA', 'Salida (Desde Planta)'), ('ENTRADA', 'Entrada (Hacia Planta)')], default='SALIDA', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('BUS', 'Bus'), ('MINIBUS', 'Minibús'), ('VAN', 'Van'), ('VAN_EMPRESA', 'Van-Empresa'), ('AUTO', 'Automóvil'), ('CAMIONETA', 'Camioneta')], max_length=20),
        ),
    ]
