# Generated by Django 6.0.1 on 2026-02-07 01:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Planta - Centro, Planta - Los Niches', max_length=100)),
                ('origen', models.CharField(default='Planta Aurora', max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('valor_servicio', models.IntegerField(help_text='Costo pactado por este trayecto')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('BUS', 'Bus'), ('MINIBUS', 'Minibus'), ('VAN', 'Van'), ('AUTO', 'Automovil'), ('CAMIONETA', 'Camioneta')], max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cantidad_pasajeros', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ocupacion_porcentaje', models.FloatField(default=0, editable=False)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.conductor')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.vehiculo')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transporte.ruta')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
