# Generated by Django 6.0.1 on 2026-02-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_conductor_nombre_empresa_externa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrosalida',
            options={'ordering': ['-fecha_registro', '-id']},
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='modelo',
        ),
        migrations.AddField(
            model_name='registrosalida',
            name='paradas_intermedias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
