# Generated by Django 6.0.1 on 2026-02-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_ruta_alter_vehiculo_tipo_registrosalida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='valor_servicio',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='costo_fijo_diario',
        ),
        migrations.AddField(
            model_name='registrosalida',
            name='valor_viaje',
            field=models.IntegerField(default=0, help_text='Costo final del servicio (Editable por Admin)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tarifa_base',
            field=models.IntegerField(default=0, help_text='Costo estándar por servicio de este vehículo'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(help_text='Ej: Planta - Centro', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='costo_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('BUS', 'Bus'), ('MINIBUS', 'Minibús'), ('VAN', 'Van'), ('AUTO', 'Automóvil'), ('CAMIONETA', 'Camioneta')], max_length=20),
        ),
    ]
