# Generated by Django 6.0.1 on 2026-02-08 02:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_remove_ruta_valor_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosalida',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
